{
 "title": "Corda Node Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Load",
   "type": "singlestat",
   "description": "It indicates Hight CPU Utilization if the CPU utilization crosses 90%  over an average of 5 minute period.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(java_lang_OperatingSystem_SystemCpuLoad[5m])"
    }
   ]
  },
  {
   "title": "Java Heap Memory",
   "type": "singlestat",
   "description": "It indicates Low Memory if the Java Heap Space utilization crosses 90%  over an average of 5 minute period.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(java_lang_Memory_HeapMemoryUsage_used[5m]) / java_lang_Memory_HeapMemoryUsage_max"
    }
   ]
  },
  {
   "title": "Flow Error Rate",
   "type": "singlestat",
   "description": "The last minute's error flow rate reaching a significant percentage (10%) of the last minute's started flow rate indicates high flow error rates.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(net_corda_Flows_OneMinuteRate{name=\"ErrorPerMinute\"} / ignoring(name) net_corda_Flows_OneMinuteRate{name=\"StartedPerMinute\"}) >= 0"
    }
   ]
  },
  {
   "title": "Message Processing Latency",
   "type": "singlestat",
   "description": "Assuming we have received enough messages in the last minute (at least 3 per second) to make a decision,- we can flag up an error if 25% of the messages took significantly (at least 50%) longer than the average message process duration. ",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(net_corda_P2P_75thPercentile{name=\"ReceiveDuration\"} / (net_corda_P2P_Mean{name=\"ReceiveDuration\"}  * 1.5) ) * (net_corda_P2P_OneMinuteRate{name=\"ReceiveDuration\"} > bool 3) "
    }
   ]
  },
  {
   "title": "Network Paramater Update",
   "type": "singlestat",
   "description": "This indicates when a network parameter update has been proposed that has not been accepted yet.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "net_corda_NetworkParameter_Value{name=\"UpdateProposed\"}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "singlestat",
   "description": "It indicates if the node is not reachable.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Dropped Signing Events",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "net_corda_Metering_Count{name=\"droppedCounts\"}"
    }
   ]
  },
  {
   "title": "Total Signing Events",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "net_corda_Metering_Count{name=\"totalCounts\"}",
     "legendFormat": "Total Signing Events"
    }
   ]
  },
  {
   "title": "Attachment Count",
   "type": "gauge",
   "description": "Total number of attachments in the node",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "targets": [
    { "expr": "net_corda_Attachments_Count", "legendFormat": "Attachments Count" }
   ]
  },
  {
   "type": "bargauge",
   "description": "Total number of successful and errored flows",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "net_corda_Flows_Count{name=\"Success\"}",
     "legendFormat": "Successful Flows"
    },
    {
     "expr": "net_corda_Flows_Count{name=\"Error\"}",
     "legendFormat": "Errored Flows"
    }
   ]
  },
  {
   "title": "Send Queue Size",
   "type": "gauge",
   "description": "The size of the in-memory send queue in the state machine for messages waiting to be sent to Artemis",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "net_corda_P2P_Value{name=\"SendQueueSize\"}",
     "legendFormat": "Send Queue Size"
    }
   ]
  },
  {
   "title": "Flow Waiting Queue Size",
   "type": "gauge",
   "description": "The number of flows waiting to be executed.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "net_corda_Flows_Value{name=\"QueueSize\"}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "DBTransactionStorage",
   "type": "bargauge",
   "description": "Weight Based Transactions  Cache",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "net_corda_Caches_Count{component=\"DBTransactionStorage_transactions\", name=\"hits\"}",
     "legendFormat": "Hits"
    },
    {
     "expr": "net_corda_Caches_Count{component=\"DBTransactionStorage_transactions\", name=\"misses\"}",
     "legendFormat": "Mises"
    },
    {
     "expr": "net_corda_Caches_Count{component=\"DBTransactionStorage_transactions\", name=\"evictions\"}",
     "legendFormat": "Evictions"
    },
    {
     "expr": "net_corda_Caches_Count{component=\"DBTransactionStorage_transactions\", name=\"loads\"}",
     "legendFormat": "Loads"
    }
   ]
  },
  {
   "title": "DBTransactionStorage Cache Load",
   "type": "gauge",
   "description": "The current size of the cache expressed as a percentage of the maximum",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "net_corda_Caches_Value{component=\"DBTransactionStorage_transactions\", name=\"weightPercent\"}"
    }
   ]
  },
  {
   "title": "Hibernate SessionFactory Cache",
   "type": "bargauge",
   "description": "Size Based Cache for Hibernate Session Factories",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "net_corda_Caches_Count{component=\"HibernateConfiguration_sessionFactories\", name=\"hits\"}",
     "legendFormat": "Hits"
    },
    {
     "expr": "net_corda_Caches_Count{component=\"HibernateConfiguration_sessionFactories\", name=\"misses\"}",
     "legendFormat": "Misses"
    },
    {
     "expr": "net_corda_Caches_Count{component=\"HibernateConfiguration_sessionFactories\", name=\"evictions\"}",
     "legendFormat": "Evictions"
    },
    {
     "expr": "net_corda_Caches_Count{component=\"HibernateConfiguration_sessionFactories\", name=\"loads\"}",
     "legendFormat": "Loads"
    }
   ]
  },
  {
   "title": "Hibernate SessionFactory Cache Load",
   "type": "gauge",
   "description": "The current size of the cache expressed as a percentage of the maximum",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
   "targets": [
    {
     "expr": "net_corda_Caches_Value{component=\"HibernateConfiguration_sessionFactories\", name=\"sizePercent\"}"
    }
   ]
  },
  { "title": "Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "System Resource Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad * 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg_over_time(java_lang_Memory_HeapMemoryUsage_used [5m]) / java_lang_Memory_HeapMemoryUsage_max * 100",
     "legendFormat": "JPA Heap Memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Java Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 23 },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used / java_lang_Memory_HeapMemoryUsage_max * 100",
     "legendFormat": "Java Heap Memory Usage"
    }
   ]
  },
  { "title": "Flow Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Active Flows",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_corda_Flows_Value{name=\"ActiveThreads\"}",
     "legendFormat": "Active Threads"
    },
    {
     "expr": "net_corda_Flows_Value{name=\"InFlight\"}",
     "legendFormat": "InFlight Flows"
    }
   ]
  },
  {
   "title": "Checkpointing Rate",
   "type": "graph",
   "description": "The rate at which checkpointing events are happening.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "per second" }
   ],
   "targets": [
    {
     "expr": "rate(net_corda_Flows_Count{name=\"Checkpointing Rate\"}[1m])",
     "legendFormat": "1 min rate"
    },
    {
     "expr": "rate(net_corda_Flows_Count{name=\"Checkpointing Rate\"}[5m])",
     "legendFormat": "5 min Rate"
    },
    {
     "expr": "rate(net_corda_Flows_Count{name=\"Checkpointing Rate\"}[15m])",
     "legendFormat": "15 min Rate"
    },
    {
     "expr": "rate(net_corda_Flows_Count{name=\"Checkpointing Rate\"}[30m])",
     "legendFormat": "30 min Rate"
    }
   ]
  },
  {
   "title": "Flow Rates",
   "type": "graph",
   "description": "One minute moving average of started and errored flows. Flow  rate measured at a five-minute basis",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "per minute" }
   ],
   "targets": [
    {
     "expr": "net_corda_Flows_FiveMinuteRate{name=\"StartedPerMinute\"}",
     "legendFormat": "Started Flows"
    },
    {
     "expr": "net_corda_Flows_FiveMinuteRate{name=\"ErrorPerMinute\"}",
     "legendFormat": "Errored Flows"
    }
   ]
  },
  {
   "title": "Flow Waiting Queue Histogram",
   "type": "graph",
   "description": "Histogram showing the queue size at the point new flows are added",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_corda_Flows_Min{name=\"QueueSizeOnInsert\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "net_corda_Flows_Mean{name=\"QueueSizeOnInsert\"}",
     "legendFormat": "Mean"
    },
    {
     "expr": "net_corda_Flows_50thPercentile{name=\"QueueSizeOnInsert\"}",
     "legendFormat": "Median"
    },
    {
     "expr": "net_corda_Flows_75thPercentile{name=\"QueueSizeOnInsert\"}",
     "legendFormat": "75th Percentile"
    },
    {
     "expr": "net_corda_Flows_95thPercentile{name=\"QueueSizeOnInsert\"}",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "net_corda_Flows_Max{name=\"QueueSizeOnInsert\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "P2P Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive Latency Histogram",
     "type": "graph",
     "description": "The latency between receiving a P2P message and delivering it to the state machine.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "net_corda_P2P_Min{name=\"ReceiveDuration\"}",
       "legendFormat": "Min"
      },
      {
       "expr": "net_corda_P2P_Mean{name=\"ReceiveDuration\"}",
       "legendFormat": "Mean"
      },
      {
       "expr": "net_corda_P2P_50thPercentile{name=\"ReceiveDuration\"}",
       "legendFormat": "Median"
      },
      {
       "expr": "net_corda_P2P_75thPercentile{name=\"ReceiveDuration\"}",
       "legendFormat": "75th Percentile"
      },
      {
       "expr": "net_corda_P2P_95thPercentile{name=\"ReceiveDuration\"}",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "net_corda_P2P_99thPercentile{name=\"ReceiveDuration\"}",
       "legendFormat": "99th Percentile"
      }
     ]
    },
    {
     "title": "Send Latency Histogram",
     "type": "graph",
     "description": "The latency when sending P2P messages, between send and send acknowledge by Artemis",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "net_corda_P2P_Min{name=\"SendLatency\"}",
       "legendFormat": "Min"
      },
      {
       "expr": "net_corda_P2P_Mean{name=\"SendLatency\"}",
       "legendFormat": "Mean"
      },
      {
       "expr": "net_corda_P2P_50thPercentile{name=\"SendLatency\"}",
       "legendFormat": "Median"
      },
      {
       "expr": "net_corda_P2P_75thPercentile{name=\"SendLatency\"}",
       "legendFormat": "75th Percentile"
      },
      {
       "expr": "net_corda_P2P_95thPercentile{name=\"SendLatency\"}",
       "legendFormat": "95th Percentile"
      },
      {
       "expr": "net_corda_P2P_99thPercentile{name=\"SendLatency\"}",
       "legendFormat": "99th Percentile"
      }
     ]
    },
    {
     "title": "Received Messages Rate",
     "type": "graph",
     "description": "A number of messages received per second.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "per second" }
     ],
     "targets": [
      {
       "expr": "rate(net_corda_P2P_Count{name=\"ReceiveDuration\"}[1m])",
       "legendFormat": "1 min Rate"
      },
      {
       "expr": "rate(net_corda_P2P_Count{name=\"ReceiveDuration\"}[5m])",
       "legendFormat": "5 min Rate"
      },
      {
       "expr": "rate(net_corda_P2P_Count{name=\"ReceiveDuration\"}[15m])",
       "legendFormat": "15 min Rate"
      },
      {
       "expr": "rate(net_corda_P2P_Count{name=\"ReceiveDuration\"}[30m])",
       "legendFormat": "30 min Rate"
      }
     ]
    },
    {
     "title": "Send Message Rate",
     "type": "graph",
     "description": "A number of messages sent per second.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "per second" }
     ],
     "targets": [
      {
       "expr": "rate(net_corda_P2P_Count{name=\"SendLatency\"}[1m])",
       "legendFormat": "1 min rate"
      },
      {
       "expr": "rate(net_corda_P2P_Count{name=\"SendLatency\"}[5m])",
       "legendFormat": "5 min rate"
      },
      {
       "expr": "rate(net_corda_P2P_Count{name=\"SendLatency\"}[15m])",
       "legendFormat": "15 min rate"
      },
      {
       "expr": "rate(net_corda_P2P_Count{name=\"SendLatency\"}[30m])",
       "legendFormat": "30 min rate"
      }
     ]
    }
   ]
  }
 ]
}