{
 "title": "Corda Network Overview",
 "description": "All Corda nodes should be scraped under one job_name: \"corda\"",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "My Corda Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"corda\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "targets": [
    { "expr": "java_lang_Runtime_Uptime", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "CPU Usage (5m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"corda\"}[5m])*100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Flows Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "net_corda_Flows_Count{name=\"Finished\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Flows Started",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 4 },
   "targets": [
    {
     "expr": "net_corda_Flows_Count{name=\"Started\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage (Heap)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Notary Flow Duration (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "net_corda_FlowDuration_FiveMinuteRate{node=\"notary\"}"
    }
   ]
  },
  {
   "title": "Flow Count by Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_corda_FlowDuration_Count{job=\"corda\"}",
     "legendFormat": "{{ instance }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Flows In Flight",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "expr": "net_corda_Flows_Value{name=\"InFlight\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Checkpoint Rate (5m)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "rate(net_corda_Flows_Count{name=\"CheckpointVolumeBytesPerSecondHist\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}